### ISSUE TITLE
landing site 

### ISSUE THREAD

**Issue by softloud** [jenrichmond/AIMOSworkshop#1]
Onur made a great landing site for the recent HLF [workshop](http://www.onurvarol.com/hlf-workshop/) I attended. 

I've made lots of distill and blogdown (truth be told too many that have been burnt and I've left a trail of ghost blogs that I haven't deleted the domains thereof..). Anyway. I guess this is something I should try on my fork.

**Comment by softloud** [comment]
Stay tuned! I have a forkable offensive!

**Comment by jenrichmond** [comment]
Ooo this is a pretty slick site. I like the simplicity. Fork it up!

**Comment by jenrichmond** [comment]
oh wow, when I reply to an email it ends up here!! i learn new things about git every day
