### ISSUE TITLE
hackathon documentation

### ISSUE THREAD

**Issue by softloud** [jenrichmond/AIMOSworkshop#8]
- [x] link to googledoc
- [x] read over and see if anything else needs to be added to description

**Comment by jenrichmond** [comment]
love this additional detail Charles, a few edits??

Technical implementation in .Rmd; ---- surprisingly I think the templates on the Rstudio website are ppt and keynote, maybe remove this bulletpoint. 

The intellectual rigour required to master a statistical computing task **is not to be underestimated**. However, there is another consideration, that frequently proves to be **even** more challenging to overcome. When we are tired, harried, or have several other things to do, if a task will require a significant investment of a cognitive energy, we may well leave that task for another day.

...

To optimise a walkthrough, we propose it must have both extrinsic and intrinsic incentives. The extrinsic incentive is, in a research context, a given. But we propose building a walkthrough **with** the objective of meritget.

**Comment by softloud** [comment]
I'm updating this as a discussion point. We don't need to decide now. It
might be _faster_ to do the first draft in `posterdown::` and the final
prettified with sketches etc. in keynote. Seeing as we have a limited time
frame... anyway, I'm goign to write this up. I think this is a really great
note about the templates.

Do be sure to go in and smooth over any edits that jump out at you - you
have the power, I sync to your version.

close #8
